name: CurseForge Upload

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Addon Zip
        run: |
          zip -r RobUI.zip RobUI_CombatGrid Robui rca

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE }}
          project_id: "1420778"
          game_endpoint: wow
          file_path: RobUI.zip
          release_type: release
          display_name: RobUI ${{ github.event.release.tag_name }}
          changelog: ${{ github.event.release.body }}
          changelog_type: markdown
